# Общая информация:
# Полностью асинхронно!
# Акриен тоже идёт нахуй!
# Кардинальная защита на уровне пакетов.
# В целях оптимизации, проверки видимости блоков не производятся в аду и энде и защищены только алмазы, золото и железо.


# Полностью защищает от xray bypass и от nocom.
# Не защищает от ускорения поиска руд путём простукивания блоков, находящихся в прямой видимости.
# Чтобы минимизировать потенциальный ущерб от последнего, установите update-radius в paper.yml равным 1.
check-receiving: true


# Полностью защищает от xray bypass и от ускорения поиска руд путём простукивания блоков, находящихся в прямой видимости.
# Не защищает от nocom. Не конфликтует с check-receiving.
# ВНИМАНИЕ: эта функция сломает обычный антиxrayй, если update-radius в paper.yml не будет равен 1.
# По умолчанию false, так как это вызывает задержку в обновлении блоков при копании, которая заметна даже при малом пинге.
check-sending: false